name: Spring Boot 프로젝트를 EC2로 배포하기 연습

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH로 EC2 에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        #uses: appleboy/ssh-action@v1.2.0
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: APPLICATION_PROPERTIES
          script_stop: true
          script: |
            cd /home/ubuntu/github-actions-practice-springboot
            rm -rf src/main/resources/application.yml || true
            git pull origin main
            mkdir -p src/main/resources
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml
            ./gradlew clean build     # .jar 파일 생성 - 전체 프로젝트를 빌드하고, 테스트도 확인/일반적인 CI/CD 파이프라인에서 자주 사용
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > .output.log 2>&1 &
